name: Deploy to Fly

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy app
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy db
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd db
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DB_API_TOKEN }}
